### ISSUE TITLE
Foreign Key Constraint Failure

### ISSUE THREAD

**Issue by samjoshai** [solrudev/Ackpine#68] opened 2024-06-28 21:33 UTC
Hi there! 
Thanks for writing such a nice wrapper for the PackageInstaller API. Occasionally, when launching an install session with the session.await() call, the following exception is thrown: 
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)

Is this a known issue?

Thank you!

**Comment by solrudev** [comment] 2024-06-29 05:01
@samjoshai Can you pinpoint the exact conditions in which the exception occurs? It'd be great if you provided a reproduction sample or at least the full exception stack trace.

**Comment by samjoshai** [comment] 2024-06-29 05:45
@solrudev Ah yes of course. I know better than to posit such an abstract question. My apologies! Here is the full stack trace:
[stackTrace.txt](https://github.com/user-attachments/files/16038918/stackTrace.txt)

As for reproducing the issue, it seems to happen randomly. I can perform many successful installations, then once in a while it fails with the exception above. Here is the configuration for the session:
`val newSession = installer.createSession(uri) {
            confirmation = Confirmation.IMMEDIATE
            installerType = InstallerType.SESSION_BASED
            name = fileName
            requireUserAction = false
        }`

**Comment by solrudev** [comment] 2024-06-29 06:34
@samjoshai I think I've identified a likely cause for this issue. Please test the `0.6.2-SNAPSHOT` version (hosted on [Sonatype `snapshots` repository](https://s01.oss.sonatype.org/content/repositories/snapshots/)) and get back with feedback.

**Comment by solrudev** [comment] 2024-06-29 07:40
@samjoshai Sorry, after further analysis I figured that the change I've made in the snapshot version most probably wouldn't fix the issue. I'll investigate more.

**Comment by solrudev** [comment] 2024-06-29 15:46
@samjoshai Please try the updated `0.6.2-SNAPSHOT` version now. I introduced some synchronization to try to fix race condition which may lead to the foreign key constraint failure.

**Comment by samjoshai** [comment] 2024-06-29 18:55
With the updated changes, I have gotten the exception three times out of around 40 or so installations. It does seems less prevalent. I am just going back and forth between installing a few apps, relaunching the updater from Android Studio, and installing a few apps. It does seem less frequent now.

**Comment by solrudev** [comment] 2024-06-29 20:30
@samjoshai Have you tried the first iteration of the snapshot version before? If so, make sure that `0.6.2-20240629.153659-2` is the version used, because Gradle may have cached previous `SNAPSHOT` version and not updated it.

**Comment by samjoshai** [comment] 2024-06-30 01:50
@solrudev With the version: 
> 0.6.2-20240629.153659-2
I seem the get the issue frequently. 

Have you experienced this behavior before, or am I the only one observing this?
I am starting to wonder if I am launching the session's coroutine in a poor place.

**Comment by samjoshai** [comment] 2024-06-30 17:21
@solrudev I think that did the trick. I haven't gotten the exception so far. I will reach out to let you know if it happens again though. Thank you for your assistance, and thank you for creating this library! When can these changes be expected on a release version of the library?

**Comment by solrudev** [comment] 2024-07-01 04:05
@samjoshai
>I think that did the trick. I haven't gotten the exception so far.

That's great to know!

>When can these changes be expected on a release version of the library?

New version will be released in a couple of days.

**Closed** 2024-07-02 07:02 UTC
Labels: bug

**Comment by solrudev** [comment] 2024-07-02 07:58
If you have time, please take the survey and share your feedback about developer experience with Ackpine. Will be much appreciated!

Survey: https://forms.gle/REgYhPQJ19VoveeVA

**Comment by samjoshai** [comment] 2024-07-02 15:31
@solrudev Thank you again for your assistance with this. Apologies for having to ask, but what version of the library should be imported with these merged changes now? Thank you.

**Comment by solrudev** [comment] 2024-07-02 15:43
@samjoshai

>what version of the library should be imported with these merged changes now?

0.7.0 version including the fix was released today.
